Areas/Admin/Models/CityStateViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BookShop.Areas.Admin.Models
{
    public class CityState
    {
        [Key]
        public int CSNo{get;set;}

        public string State{get; set;}

        public string City {get; set;}
    }
}

Areas/Admin/Controllers/CityStateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace BookShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CityStateController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Areas/Admin/Views/CityState/Index.cshtml
@using BookShop.Areas.Admin.Models;
@model CityState 
@{
    ViewData["Title"] = "CityState Page";
}

<h1>welcome to CityState</h1>
<script>
    function onclear()
    {
        document.getElementById("City").value="";
    }
</script>
<div>
     @using (Html.BeginForm("Index","CityState",FormMethod.Post))
     {
                <label asp-for="CityStateNo">CityState :</label>
                @Html.TextBoxFor(m=>m.CityStateNo)<br/><br/>

                <label asp-for="City">City :</label>
                @Html.TextBoxFor(m=>m.City)<br/><br/>

                <label asp-for="CityStateNo">State :</label>
                @Html.TextBoxFor(m=>m.State)<br/><br/>
                <button onclick="onclear()">reset</button>
                <input type="submit" >

     }
</div>